name: Deploy to EC2 CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo ">>> Navigating to project directory..."
            cd ${{ secrets.PROJECT_PATH }}    # bu endi mavjud papka bo‘lishi kerak

            echo ">>> Pulling latest changes from Git..."
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            echo ">>> Installing backend dependencies and restarting/reloading..."
            cd backend
            npm install --production

            pm2 reload ${{ secrets.BACKEND_APP_NAME }} || pm2 start server.js --name "${{ secrets.BACKEND_APP_NAME }}"
            pm2 save

            echo ">>> Installing frontend dependencies and building..."
            cd ../frontend
            npm install
            npm run build

            echo ">>> Deployment to EC2 finished!"
