name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myproject
            git pull origin main
            source venv/bin/activate
            pip install -r backend/requirements.txt
            python backend/manage.py migrate
            python backend/manage.py collectstatic --noinput
            pm2 restart backend

            cd frontend
            npm install
            npm run build
            pm2 restart frontend
