name: Deploy to EC2

on:
  push:
    branches:
      - main # Yoki sizning asosiy deployment branch'ingiz

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Loyihangizga mos Node.js versiyasini kiriting

      # (Ixtiyoriy) Frontend build qilish va artefakt sifatida saqlash (agar serverda build qilishni xohlamasangiz)
      # - name: Build Frontend
      #   run: |
      #     cd frontend # Frontend papkasiga yo'l
      #     npm install
      #     npm run build
      # - name: Upload Frontend Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: frontend-build
      #     path: frontend/build # Build papkasiga yo'l

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            set -e # Xatolik yuz berganda scriptni to'xtatish

            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main # Yoki sizning branch'ingiz

            echo ">>> Installing backend dependencies..."
            cd backend # Backend papkasiga yo'l
            npm install --production # Faqat production bog'liqliklarni o'rnatish
            # Agar backend build qilinishi kerak bo'lsa (masalan, TypeScript):
            # npm run build

            echo ">>> Restarting backend with PM2..."
            pm2 reload ${{ secrets.BACKEND_APP_NAME }} || pm2 start your-main-server-file.js --name "${{ secrets.BACKEND_APP_NAME }}" # Yoki pm2 restart
            pm2 save # O'zgarishlarni saqlash

            echo ">>> Installing frontend dependencies and building..."
            cd ../frontend # Frontend papkasiga yo'l
            npm install
            # Agar .env fayli kerak bo'lsa, uni GitHub secrets dan yaratishingiz mumkin
            # echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
            npm run build

            echo ">>> Deployment finished!"